### ISSUE TITLE
The icons disappeared after JB

### ISSUE THREAD

**Issue by piaomiaoguhong10** [dora2-iOS/daibutsu#1]
I used Daibutsu to jb my iPad mini. The success rate is rather good but the icons disappeared after jb. The home screen went blank.

**Comment by dora2-iOS** [comment]
This issue was finally fixed in ipa v1.1 & untether v1.2.3. Thank you for reporting!

**Comment by dora2-iOS** [comment]
For reference. This problem can be solved by running patcyh's extrainst_ at the first bootup. https://github.com/dora2-iOS/daibutsu/blob/main/untether/untether32.c#L1292
